# Generated by Django 6.1 on 2026-08-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('teacher', 'Учитель'), ('accountant', 'Бухгалтер'), ('developer', 'Разработчик')], default='teacher', max_length=20, verbose_name='Роль'),
        ),
    ]
