# Generated by Django 6.1 on 2026-08-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_payment_is_partial_payment_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('group', 'Групповая'), ('individual', 'Индивидуальная')], default='group', max_length=20, verbose_name='Тип'),
        ),
    ]
