# Generated by Django 6.1 on 2026-08-31 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_student_age_student_grade_student_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название книги')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='Фото обложки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='book_needed',
            field=models.BooleanField(default=False, verbose_name='Требуется книга'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='has_book',
            field=models.BooleanField(default=False, verbose_name='Есть книга'),
        ),
        migrations.AddField(
            model_name='group',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='dashboard.book', verbose_name='Книга'),
        ),
    ]
