# Generated by Django 6.1 on 2026-09-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_book_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='group_photos/', verbose_name='Фото группы'),
        ),
    ]
