# Generated by Django 6.1 on 2026-09-01 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_group_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='group_teachers', to=settings.AUTH_USER_MODEL, verbose_name='Дополнительные учителя'),
        ),
    ]
