# Generated by Django 6.1 on 2026-09-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_group_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ставка в час (₸)'),
        ),
    ]
