# Generated by Django 6.1 on 2026-09-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_student_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration_hours',
            field=models.DecimalField(decimal_places=1, default=1.5, max_digits=4, verbose_name='Длительность (часов)'),
        ),
    ]
