# Generated by Django 5.2 on 2026-09-01 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_attendance_id_alter_book_id_and_more'),
        ('dashboard', '0008_group_teachers'),
    ]

    operations = [
    ]
