# Generated by Django 6.1 on 2026-09-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_group_teachers'),
        ('dashboard', '0009_lesson_duration_hours'),
    ]

    operations = [
    ]
