# Generated by Django 6.1 on 2026-09-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_merge_0008_group_teachers_0009_lesson_duration_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='duration_hours',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hourly_rate',
        ),
    ]
