# Generated by Django 5.2 on 2026-09-17 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_merge_20260901_1622'),
        ('dashboard', '0012_scheduleslot'),
    ]

    operations = [
    ]
