# Generated by Django 6.1 on 2026-09-19 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_scheduleslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(verbose_name='Номер страницы')),
                ('image', models.ImageField(upload_to='book_pages/', verbose_name='Изображение страницы')),
                ('audio', models.FileField(blank=True, null=True, upload_to='book_audio/', verbose_name='Аудио')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='dashboard.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Страница книги',
                'verbose_name_plural': 'Страницы книг',
                'ordering': ['page_number'],
                'unique_together': {('book', 'page_number')},
            },
        ),
    ]
