# Generated by Django 6.1 on 2026-09-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_bookpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='books_pdf/', verbose_name='PDF книги'),
        ),
        migrations.DeleteModel(
            name='BookPage',
        ),
    ]
