# Generated by Django 5.2 on 2026-09-19 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_merge_0009_merge_20260901_1622_0012_scheduleslot'),
        ('dashboard', '0014_book_pdf_file_delete_bookpage'),
    ]

    operations = [
    ]
