# Generated by Django 6.1 on 2026-09-27 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_group_books_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='dashboard.book', verbose_name='Запрошенная книга'),
        ),
    ]
