# Generated by Django 6.1 on 2026-10-06 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_remove_group_price_student_price_per_lesson_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='homework_done',
            field=models.BooleanField(default=False, verbose_name='Домашка сделана'),
        ),
        migrations.CreateModel(
            name='LevelCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('up', 'Уровень выше'), ('down', 'Уровень ниже')], max_length=10, verbose_name='Направление')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibrations', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='dashboard.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='dashboard.student')),
            ],
            options={
                'verbose_name': 'Калибровка уровня',
                'verbose_name_plural': 'Калибровки уровня',
                'ordering': ['-created_at'],
            },
        ),
    ]
