# Generated by Django 6.1 on 2026-10-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_attendance_homework_done_levelcalibration'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='cycle_start_day',
            field=models.IntegerField(default=11, help_text='Число месяца, с которого начинается учебный цикл (2-28). Если 6 — цикл идёт с 6 числа этого месяца по 5 число следующего.', verbose_name='День начала цикла'),
        ),
    ]
