# Generated by Django 6.1 on 2026-10-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_group_cycle_start_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='star_earned',
            field=models.BooleanField(default=False, verbose_name='Звезда за урок'),
        ),
    ]
